# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2024 Rockchip Electronics Co., Ltd
#
# Makefile for Bosch ICM42680 IMU
#
obj-$(CONFIG_ICM42680) += icm42680.o
icm42680-objs := icm42680_core.o icm42680_trigger.o icm42680_ring.o
obj-$(CONFIG_ICM42680_I2C) += icm42680_i2c.o
